-- FAF mod vault: every upload needs a NEW uid and a HIGHER version.
-- For the next release: version = 2 and a fresh uid (any new GUID).
name = "DualGap AI"
uid = "6d1f3a52-9c4e-4b8a-a2f7-d17e0c5b9a14"
version = 1
copyright = "2026 Constantine Vlasov"
description = "Role-based skirmish AI for Dual Gap Adaptive v14 (6v6). Each bot reads its spawn and plays GROUND, NAVAL, AIR or ECO. Pick 'AI: DualGap (beta)' or 'AIx: DualGap (beta)' in the lobby. First test version."
author = "Constantine Vlasov"
url = "https://github.com/jaxxtrend/faf-dualgap-ai"
icon = ""
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}
